name: Build
on:
  push:
    branches:
      - master # or the name of your main branches
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://sonarsource/sonar-scanner-cli
        with: 
          projectBaseDir: /home/ubuntu/arachni/
          args: >
            -Dsonar.projectKey=Test_Project
            -Dsonar.login=admin
            -Dsonar.password=Kunal@1996
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
